# Generated by Django 2.0.2 on 2018-07-29 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=25)),
                ('guessed_word', models.CharField(default='', max_length=15)),
                ('status', models.CharField(default='ongoing', max_length=10)),
                ('wins_total', models.IntegerField(default=0)),
                ('losses_total', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
