# Generated by Django 2.0.2 on 2018-07-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangman',
            old_name='datetime',
            new_name='playtime',
        ),
    ]
