# Generated by Django 2.0.2 on 2018-07-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_remove_hangman_playtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangman',
            old_name='game_id',
            new_name='hangman_id',
        ),
    ]
